# version: "29.5"

services:
  to-do-app-backend:
    build: .
    container_name: to-do-app-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
      - ./entrypoint.py:/entrypoint.py
    ports:
      - "8000:8000"
    env_file:
      - .env
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: on-failure
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
      - '110:110'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
